# Testing ResFinder

image: python:3.10

pipelines:
  custom:
    build-and-test:
      - step:
          name: Test
          caches:
            - pip
          script:
            - pip install --upgrade pipenv wheel
            - pipenv install --dev
            - pipenv run build
            - pipenv run test
