# Testing ResFinder

image: python:3.10

pipelines:
  custom:
    build-and-test:
      - step:
          name: Test
          caches:
            - pip
          script:
            - git clone https://git@bitbucket.org/genomicepidemiology/resfinder_db.git
            - git clone https://git@bitbucket.org/genomicepidemiology/pointfinder_db.git
            - pip install --upgrade pipenv wheel
            - pipenv install --dev
            - pipenv run build
            - pipenv run test
